// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: https://github.com/nhatthm/mockery-template

package mock

import (
	"net/http"
	"net/url"
	"testing"

	mock "github.com/stretchr/testify/mock"
)

// JarMocker is a func that creates a Jar mock. It is used to compose
// mock expectations from other packages without exposing *testing.T.
type JarMocker func(tb testing.TB) *Jar

// NopJar is a Jar mock with no expectation.
var NopJar = MockJar()

// MockJar creates a new Jar mock with cleanup to ensure all the expectations are met.
func MockJar(mocks ...func(jar *Jar)) JarMocker {
	return func(tb testing.TB) *Jar {
		tb.Helper()

		jar := NewJar(tb)

		for _, configure := range mocks {
			configure(jar)
		}

		return jar
	}
}

// NewJar creates a new instance of Jar. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJar(t interface {
	mock.TestingT
	Cleanup(func())
}) *Jar {
	mock := &Jar{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Jar is an autogenerated mock type for the CookieJar type
type Jar struct {
	mock.Mock
}

type Jar_Expecter struct {
	mock *mock.Mock
}

func (_m *Jar) EXPECT() *Jar_Expecter {
	return &Jar_Expecter{mock: &_m.Mock}
}

// Cookies provides a mock function for the type Jar
func (_mock *Jar) Cookies(u *url.URL) []*http.Cookie {
	ret := _mock.Called(u)

	if len(ret) == 0 {
		panic("no return value specified for Cookies")
	}

	var r0 []*http.Cookie
	if returnFunc, ok := ret.Get(0).(func(*url.URL) []*http.Cookie); ok {
		r0 = returnFunc(u)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*http.Cookie)
		}
	}
	return r0
}

// Jar_Cookies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cookies'
type Jar_Cookies_Call struct {
	*mock.Call
}

// Cookies is a helper method to define mock.On call
//   - u *url.URL
func (_e *Jar_Expecter) Cookies(u any) *Jar_Cookies_Call {
	return &Jar_Cookies_Call{Call: _e.mock.On("Cookies", u)}
}

func (_c *Jar_Cookies_Call) Run(run func(u *url.URL)) *Jar_Cookies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *url.URL
		if args[0] != nil {
			arg0 = args[0].(*url.URL)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Jar_Cookies_Call) Return(cookies []*http.Cookie) *Jar_Cookies_Call {
	_c.Call.Return(cookies)
	return _c
}

func (_c *Jar_Cookies_Call) RunAndReturn(run func(u *url.URL) []*http.Cookie) *Jar_Cookies_Call {
	_c.Call.Return(run)
	return _c
}

// SetCookies provides a mock function for the type Jar
func (_mock *Jar) SetCookies(u *url.URL, cookies []*http.Cookie) {
	_mock.Called(u, cookies)
	return
}

// Jar_SetCookies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCookies'
type Jar_SetCookies_Call struct {
	*mock.Call
}

// SetCookies is a helper method to define mock.On call
//   - u *url.URL
//   - cookies []*http.Cookie
func (_e *Jar_Expecter) SetCookies(u any, cookies any) *Jar_SetCookies_Call {
	return &Jar_SetCookies_Call{Call: _e.mock.On("SetCookies", u, cookies)}
}

func (_c *Jar_SetCookies_Call) Run(run func(u *url.URL, cookies []*http.Cookie)) *Jar_SetCookies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *url.URL
		if args[0] != nil {
			arg0 = args[0].(*url.URL)
		}
		var arg1 []*http.Cookie
		if args[1] != nil {
			arg1 = args[1].([]*http.Cookie)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Jar_SetCookies_Call) Return() *Jar_SetCookies_Call {
	_c.Call.Return()
	return _c
}

func (_c *Jar_SetCookies_Call) RunAndReturn(run func(u *url.URL, cookies []*http.Cookie)) *Jar_SetCookies_Call {
	_c.Run(run)
	return _c
}
