# See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  misspell:
    locale: US
  unused:
    check-exported: false
  unparam:
    check-exported: true

linters:
  enable-all: true
  disable:
    - copyloopvar
    - depguard
    - execinquery
    - exhaustruct
    - exportloopref
    - forbidigo
    - gci
    - gochecknoglobals
    - gomnd
    - intrange
    - ireturn
    - lll
    - nolintlint # https://github.com/golangci/golangci-lint/issues/3063
    - nonamedreturns
    - rowserrcheck
    - tagliatelle
    - testifylint
    - varnamelen
    - wastedassign
    - wrapcheck

issues:
  exclude-use-default: false
  exclude-files:
    - dummy_publicsuffix_test.go
    - example_test.go
    - jar.go
    - jar_test.go
    - punycode.go
    - punycode_test.go
  exclude-dirs:
    - internal/ascii
  exclude-rules:
    - linters:
        - dupl
        - err113
        - funlen
        - goconst
        - goerr113
        - gomnd
        - noctx
      path: "_test.go"
