version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - ireturn
    - lll
    - mnd
    - nolintlint
    - nonamedreturns
    - rowserrcheck
    - tagliatelle
    - testifylint
    - varnamelen
    - wastedassign
    - wrapcheck
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocyclo:
      min-complexity: 20
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - err113
          - funlen
          - goconst
          - mnd
          - noctx
        path: _test.go
    paths:
      - dummy_publicsuffix_test.go
      - example_test.go
      - jar.go
      - jar_test.go
      - punycode.go
      - punycode_test.go
      - internal/ascii
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - dummy_publicsuffix_test.go
      - example_test.go
      - jar.go
      - jar_test.go
      - punycode.go
      - punycode_test.go
      - internal/ascii
      - third_party$
      - builtin$
      - examples$
