dir: mock
structname: '{{.InterfaceName}}'
pkgname: mock
template: "https://raw.githubusercontent.com/nhatthm/mockery-template/0.3.0/templates/testify-mocker.templ"
template-data:
  unroll-variadic: true
packages:
  net/http:
    config:
      include-interface-regex: CookieJar
      structname: Jar
      filename: "jar.go"
